"""cascade delete notes and refresh_tokens with user

Revision ID: 6953221284ba
Revises: 4e1981e6b11a
Create Date: 2026-07-11 16:03:20.888257

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6953221284ba"
down_revision: str | Sequence[str] | None = "4e1981e6b11a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("notes_owner_id_fkey"), "notes", type_="foreignkey")
    op.create_foreign_key(None, "notes", "users", ["owner_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(None, "refresh_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", "users", ["user_id"], ["id"])
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.create_foreign_key(op.f("notes_owner_id_fkey"), "notes", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###
